import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Headers from "@/components/headers";
import Footer from "@/components/footer";

const inter = Inter({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${inter.variable} antialiased`}>
            <div className="relative min-h-screen bg-slate-900 text-slate-50 flex flex-col items-center justify-center p-4 overflow-hidden">
               <Headers />
               {children}
               <Footer />
            </div>
         </body>
      </html>
   );
}
